# backend/report.py
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
from datetime import datetime

def generate_report(result):
    filename = "forensic_report.pdf"
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    # ---------------- Title ----------------
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2, 820, "🛡️ AI Forensic Verification Report")

    # ---------------- Metadata / Date ----------------
    c.setFont("Helvetica", 10)
    c.drawRightString(width - 50, 800, f"Generated on: {datetime.now().strftime('%d-%b-%Y %H:%M:%S')}")

    # ---------------- Verdict & Score ----------------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 770, "Scan Summary:")

    c.setFont("Helvetica", 12)
    verdict = result.get('verdict', 'Unknown')
    score = result.get('score', 0)
    media_type = result.get('media_type', 'Unknown')

    # Determine color for verdict
    if verdict.startswith("🔴"):
        color = colors.red
    elif verdict.startswith("⚠️"):
        color = colors.orange
    else:
        color = colors.green

    # Draw verdict with color
    c.setFillColor(color)
    c.drawString(70, 750, f"Verdict: {verdict}")
    c.setFillColor(colors.black)  # reset color
    c.drawString(70, 730, f"Trust Score: {score}%")
    c.drawString(70, 710, f"Media Type: {media_type}")

    # ---------------- Explanation ----------------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 680, "Analysis Explanation:")

    c.setFont("Helvetica", 12)
    explanation = result.get("why", "No explanation provided.")

    # Wrap text for explanation
    text = c.beginText(70, 660)
    text.setLeading(16)
    for line in explanation.split('\n'):
        text.textLine(line)
    c.drawText(text)

    # ---------------- Forensic Flags ----------------
    flags = result.get("flags", [])
    if flags:
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, 620 - 20*len(flags), "Forensic Flags:")

        # Create a table for flags
        table_data = [["Flag"]]
        for flag in flags:
            table_data.append([flag])

        table = Table(table_data, colWidths=[500])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.grey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN',(0,0),(-1,-1),'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 12),
            ('BOTTOMPADDING', (0,0), (-1,0), 8),
            ('GRID', (0,0), (-1,-1), 0.5, colors.black),
        ]))
        table.wrapOn(c, width, height)
        table.drawOn(c, 70, 550 - 20*len(flags))

    # ---------------- Footer ----------------
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(width / 2, 50, "Report generated by AI Deepfake Detection System")

    c.save()
    return filename
